version: "2"
services:
  ene-proxy:
    container_name: ene-proxy
    image: caddy
    depends_on:
      - ene-server
      - ene-client
    restart: always
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 7060:7060
  ene-db:
    container_name: ene-db
    image: mongo:latest
    ports:
      - 27022:27017
    volumes:
      - ./mongo:/data/db
  ene-server:
    build: ./server
    container_name: ene-server
    ports:
      - 7061:7061
    volumes:
      - ./server/app:/app
      - ./config:/app/config
    environment:
      PORT: 7061
      MONGO_ADDR: "ene-db:27017"
      ACCOUNTS_PATH: "/app/config/accounts.json"
      AUTH_EXPIRES: 3600
    env_file:
      - ./config/jwt-secret
    depends_on:
      - ene-db
    links:
      - ene-db
  ene-client:
    build: ./client
    container_name: ene-client
    ports:
      - 7062:7062
    volumes:
      - ./client/app:/app
      - ./client/app/nginx.conf:/etc/nginx/conf.d/default.conf
    stdin_open: true
    environment:
      PORT: 7062
