version: "2"
services:
  feed-proxy:
    container_name: feed-proxy
    image: caddy
    depends_on:
      - feed-server
      - feed-client
    restart: always
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 7120:7120
  feed-db:
    container_name: feed-db
    image: mongo:latest
    ports:
      - 27025:27017
    volumes:
      - ./mongo:/data/db
  feed-server:
    build: ./server
    container_name: feed-server
    ports:
      - 7121:7121
    volumes:
      - ./server/app:/app
      - ./config:/app/config
    environment:
      PORT: 7121
      MONGO_ADDR: "feed-db:27017"
      RIVER_ADDR: "http://feed-river:7130"
      ACCOUNTS_PATH: "/app/config/accounts.json"
      AUTH_EXPIRES: 3600
    env_file:
      - ./config/jwt-secret
    depends_on:
      - feed-db
      - feed-river
    links:
      - feed-db
      - feed-river
  feed-client:
    build:
      context: ./client
      dockerfile: ${CLIENT_DOCKERFILE}
    container_name: feed-client
    ports:
      - 7122:7122
    volumes:
      - ./client/app:/app
      - ./client/app/nginx.conf:/etc/nginx/conf.d/default.conf
    stdin_open: true
    environment:
      PORT: 7122
  feed-river:
    build: ../river
    container_name: feed-river
    ports:
      - 7130:7130
    environment:
      PORT: 7130
