#!/bin/bash

if [[ "$*" == *"--deploy"* ]]; then
    DOCKERFILE=Dockerfile
elif [[ "$*" == *"--develop"* ]]; then
    DOCKERFILE=Dockerfile-dev
fi

params=()

if [[ "$*" == *"--detach"* ]]; then
    params+=(-d)
fi

if [[ "$*" == *"--client"* ]]; then
    params+=(feed-client)
fi

CLIENT_DOCKERFILE=$DOCKERFILE docker-compose up --build --force-recreate "${params[@]}"
