#!/bin/bash

if [[ "$*" == *"--deploy"* ]]; then
    CLIENT_DOCKERFILE=Dockerfile
elif [ "$*" = *"--develop"* ]; then
    CLIENT_DOCKERFILE=Dockerfile-dev
fi

params=()

if [[ "$*" == *"--detach"* ]]; then
    params+=(-d)
fi

if [[ "$*" == *"--client"* ]]; then
    params+=(feed-client)
fi

docker-compose up --build --force-recreate "${params[@]}"